POST http://localhost:3003/api/blogs HTTP/1.1
content-Type: application/json 

{
 "title": "The Fat Man in space",
  "author": "Greg Newmanson",
  "url": "www.ObeseAtmosphere.com",
  "likes": 50000
}

